(add-to-list 'load-path (locate-user-emacs-file "el-get/el-get"))
(unless (require 'el-get nil 'noerror)
    (with-current-buffer
        (url-retrieve-synchronously
            "https://raw.githubusercontent.com/dimitri/el-get/master/el-get-install.el")
        (goto-char (point-max))
        (eval-print-last-sexp)))

(el-get-bundle! f)
(el-get-bundle! php-mode)
(el-get-bundle! yaml-mode)
(el-get-bundle ddskk)
(el-get-bundle zenitani/elisp)
(el-get-bundle syohex/emacs-git-gutter)
(el-get-bundle! editorconfig)
(el-get-bundle evil :info nil)
(el-get-bundle! fxbois/web-mode)
(el-get-bundle! lua-mode)
(el-get-bundle multi-term)
(el-get-bundle! Hkey/sequential-command)
(el-get-bundle! minor-mode-hack)
(el-get-bundle migemo)
(el-get-bundle! open-junk-file)
(el-get-bundle! markdown-mode)
(el-get-bundle! coffee-mode)
(el-get-bundle! ag)
(el-get-bundle jacktasia/dumb-jump)
(el-get-bundle goto-chg)
;;;(el-get-bundle! magit)
(el-get-bundle howdoi)
(el-get-bundle Wilfred/ez-query-replace.el)
(el-get-bundle! expand-region)
(el-get-bundle! emacsmirror/gnugo)
(el-get-bundle! summarye)
(el-get-bundle! eldoc-extension)
(el-get-bundle visual-regexp)
(el-get-bundle anything)
(el-get-bundle helm)
(el-get-bundle! dired-k)
(el-get-bundle! yatex)
(el-get-bundle! yasnippet)
(el-get-bundle! use-package)
(el-get-bundle! ht)
(el-get-bundle! powerline)
(el-get-bundle ace-jump-mode)
(el-get-bundle auto-complete)
(el-get-bundle! zk-phi/git-complete)
(el-get-bundle abo-abo/swiper)
(el-get-bundle m2ym/popwin-el)
(el-get-bundle! helm-ag)
(el-get-bundle! anzu)
(el-get-bundle! helm-swoop)
(el-get-bundle m2ym/direx-el)
(el-get-bundle sr-speedbar)
(el-get-bundle company-mode/company-mode)
(el-get-bundle sabof/stripe-buffer)
(el-get-bundle! abo-abo/avy)
(el-get-bundle! momomo5717/avy-migemo)
(el-get-bundle apel)
(el-get-bundle! elscreen)
(el-get-bundle! emacsmirror/rainbow-mode)
(el-get-bundle! Fanael/rainbow-delimiters)
(el-get-bundle oneKelvinSmith/monokai-emacs)
(el-get-bundle jaypei/emacs-neotree)
(require 'neotree)

(el-get-bundle! idaisukee/Yunoki)
(el-get-bundle! idaisukee/Kenrituhitiyutukuwanmahe)
(el-get-bundle! idaisukee/Kensoukahuuntoutiyau)
(el-get-bundle! idaisukee/Sakurahasi)
(el-get-bundle! idaisukee/Iriewoka)
(el-get-bundle! idaisukee/Sinsimitu)
(el-get-bundle! idaisukee/Siyakusiyomahe)
(el-get-bundle! idaisukee/Simituekimahe)
;;;(el-get-bundle! idaisukee/Nakahamatiyau)
(el-get-bundle idaisukee/Tusimati)
(el-get-bundle idaisukee/Akihamiti)
(el-get-bundle idaisukee/Nisikuho)
(el-get-bundle! idaisukee/Aisometiyau)

(if
    (or
     (string= emacs-version "24.5.1")
     (string= emacs-version "25.2.2")
     (string= emacs-version "25.3.2"))
    (el-get-bundle! magit))

(if
 (string= emacs-version "24.5.1")
 (progn
  (el-get-bundle! elpa:let-alisnt)
  (el-get-bundle! elpa:seq)
  (el-get-bundle! flycheck/flycheck)
  )
 nil)

(provide 'el-get-init)
