(defun set-alias (pair)
 (defalias (car pair) (cdr pair)))

(setq alias-pairs
 (list
  '(ho . helm-occur)
  '(dk . describe-key)
  '(dkb . describe-key-briefly)
  '(db . describe-bindings)
  '(dfa . describe-face)
  '(df . describe-function)
  '(dv . describe-variable)
  '(dm . describe-mode)
  '(ir . indent-region)
  '(ap . apropos)
  '(ff . find-function)
  '(kb . kill-buffer)
  '(kemacs . kill-emacs)
  '(id . insert-date-time)
  '(rb . revert-buffer)
  '(md . make-directory)
  '(cp . dired-do-copy)
  '(mv . dired-do-rename)
  '(cr . comment-or-uncomment-region)
  '(ucr . uncomment-region)
  '(s . smart-compile)
  '(rs . replace-string)
  '(gl . goto-line)
  '(qr . query-replace)
  '(rr . replace-regexp)
  '(ms . magit-status)
  '(find . find-name-dired)
  '(oc . occur)
  '(eglp . el-get-list-packages)
  '(rg . rgrep)
  '(er . er/expand-region)
  '(si . insert-parentheses)
  '(sn . forward-sexp)
  '(sd . backward-sexp)
  '(st . backward-up-list)
  '(sh . down-list)
))

(mapcar 'set-alias alias-pairs)
(provide 'alias-init)
