(defun ieremii-previous-window nil
 (interactive)
 (other-window -1))

(bind-keys*
 ("C-t" . previous-line)
 ("C-@" . undo)
 ("C-u" . end-of-line)
 ("C-o" . scroll-up-command)
 ("C-e" . scroll-down-command)
 ("C-S-e" . beginning-of-buffer)
 ("C-S-o" . end-of-buffer)

 ("<tab>" . execute-extended-command)
 ("M-'" . anything-M-x)
 ("C-p" . yank)
 ("C-S-p" . anything-show-kill-ring)
 ("C-d" . backward-char)
 ("C-S-z" . toggle-and-print-jitai)
 ("<backtab>" . save-buffer)
 ("M-s" . save-buffer)
 ("C-a" . beginning-of-line)
 ("C-x C-h" . skk-mode)
 ("C-S-a" . move-to-open-paren)
 ("C-S-u" . move-to-close-paren)
 ("C-x j" . ieremii-open-junk-file)
 ("C-b" . delete-backward-char)
 ("C-S-b" . ieremii-backward-kill-word)
 ("C-S-k" . ieremii-kill-line-contents)
 ("C-S-s" . isearch-backward)
 ("C-S-t" . backward-paragraph)
 ("C-S-h" . forward-paragraph)
 ("<f2>" . my-buffer-menu2)
 ("<f3>" . other-window)
 ("<f4>" . open-init-el)
 ("<f6>" . shell)
 ("C-<f6>" . eshell)
 ("<f7>" . toggle-and-print-skk-kutouten-type)
 ("<f8>" . toggle-and-print-jitai)
 ("C-<f8>" . show-lub)
 ("M-b" . find-file-and-prepare-prd-article)
 ("<f11>" . dired-pwd)
 ("C-<f11>" . dired)
 ("S-<muhenkan>" . delete-window)
 ("<left>" . backward-char)
 ("<right>" . forward-char)
 ("<up>" . previous-line)
 ("<down>" . next-line)
 ("C-r" . delete-char)
 ("C-S-r" . ieremii-kill-word)
 ("C-d" . backward-char)
 ("C-h" . next-line)
 ("C-t" . previous-line)
 ("C-n" . forward-char)
 ("C-f" . goto-last-change)
 ("C-S-f" . goto-last-change-reverse)
 ("M-o" . find-file-at-point)
 ("C-S-d" . my-backward-word)
 ("C-S-n" . exit-white-space-or-forward-word)
 ("M-o" . find-file)
 ("C-S-w" . save-buffers-kill-terminal)
 ("C-," . my-copy-region-as-kill)
 ("C-." . my-kill-region)
 ("M-d" . dired-pwd)
 ("M-b" . my-buffer-menu2)
 ("C--" . universal-argument)
 ("C-=" . goto-line)
 ("C-w" . my-search-forward)
 ("C-\"" . mark-all-pair)
 ("C-< t" . copy-whole-buffer)
 ("C-< b" . copy-block)
 ("C-'" . er/expand-region)
 ("M--" . decr-height-10)
 ("M-_" . incr-height-10)
 ("M-m" . anything-mini)
 ("M-c" . smart-compile)
 ("M-v" . evil-mode)
 ("C-k" . ieremii-kill-line)
 ("M-q" . ieremii-previous-window)
 ("M-j" . other-window)
 ("M-e" . eval-last-sexp)
 ("M-;" . delete-window)
 ("M-k" . delete-other-windows)
 ("M-u" . comment-dwim)
 ("C-z" . ieremii-next-input-mode)
 ("C-S-SPC" . ieremii-return-to-mark)
 ("C-v" . ieremii-replace-char)
 ("C-S-v" . ieremii-lookup-sauketu)
 ("M-g" . magit-status)
 )

(bind-keys :map global-map
 ("C-u" . nil)
 ("C-y" . nil)
 ("C-w" . nil)
 ("M-w" . nil)
 ("M-y" . nil)
 ("M-h" . nil)
 ("M-t" . nil)
 ("C-\\" . nil)
 ("C--" . nil)
 ("C-S-h" . nil)
 ("C-S-t" . nil)
 ("C-x C-c" . nil)
 ("C-_" . nil)
 ("C-p" . nil)
 ("C-f" . nil)
 ("C-v" . nil)
 ("C-o" . nil)
 ("<insert>" . nil)
 ("C-<insert>" . nil)
 ("C-o" . nil)
 ("<tab>" . nil)
 ("M-c" . nil)
 ("C-x C-f" . nil)
 ("<f10>" . nil)
 ("M-z" . nil))


(bind-keys :map anything-map
 ("C-a" . beginning-of-line)
 ("C-u" . end-of-line)
 ("C-d" . backward-char)
 ("M-h" . anything-next-line)
 ("M-t" . anything-previous-line)
 ("C-n" . forward-char)
 ("C-o" . anything-next-page)
 ("C-e" . anything-previous-page)
 ("C-r" . delete-char)
 ("C-b" . delete-backward-char)
 ("C-p" . yank))

(bind-keys :map minibuffer-local-map
 ("M-t" . previous-history-element)
 ("M-h" . next-history-element))


(add-hook 'markdown-mode-hook
 '(lambda ()
   (bind-keys :map markdown-mode-map
    ("C-m" . newline))))

(add-hook 'dired-mode-hook 
 '(lambda ()
   (bind-keys :map dired-mode-map
    ("e" . dired-up-directory)
    ("f" . find-file)
    ("O" . dired-open-file))))

(add-hook 'isearch-mode-hook 
 '(lambda ()
   (bind-keys :map isearch-mode-map
    ("C-S-s" . isearch-repeat-backward))))


(provide 'bind-key-init)
